openapi: 3.0.0
info:
  title: RAG API
  version: "1.0"
  description: Simple API for asking questions based on the provided documentation.
paths:
  /ask:
    post:
      summary: Ask a question about the documentation (RAG)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  example: "How do I replace the xenon lamp module on the Pentero?"
      responses:
        "200":
          description: Successful answer
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The answer extracted from the documentation
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        source:
                          type: string
                        chunkIndex:
                          type: integer
        "422":
          description: No relevant information in the documentation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "This information is not available in the provided documentation."
